### PR TITLE
fix-new-vsc-version-issue

### PR DESCRIPTION
**Pull request by elmasria**
- Updated node-abi to the latest version
- Compatibility fix with VSC 1.53.0

### CODE REVIEW

**Comment by Josverl** [comment]
@elmasria, 
Kudos for the effort in trying to solve this. But based om my experience with fixing these types of errors for the last few years errors I think you are not on the right path here.

there are usually none of the changes needed that you seem to be doing here, just download a few new bindings and put them in the corrct folders and done.
( but as there is next to no documentation on how to do that i took me more than a year to create a procedure to make this work more or less smoothly) 

it just require the maintainers to run a downloadscript  `npm run download-native ` on a regular basis and package an republish 
see documentation in /doc/multiplatformsupport.md 

perhaps I need to make the documentation cleared, but without the maintainers taking the responsibility to use the tooling that the community have provided , there is little i can do but fork.

Meanwhile to get you unstuck you can consider using a beta version from my fork : 
https://github.com/Josverl/pymakr-vsc/releases/tag/v1.1.7-beta
Download and  install a .vsix by opening the file from within VS Code. 
Run File | Open File... or kb(workbench.action.files.openFile) and select the extension .vsix.

later you can uninstall an re-join the pymakr mainline.
HTH  Jos

**Comment by elmasria** [comment]
Hi @Josverl 

Thank you for your feedback and support. 

Kindly note that I have tried already to download new bindings, but the issue we are facing now is that the serialport library throw error "TypeError: Third argument must be a function" with electron 11. 

Please check https://github.com/serialport/node-serialport/issues/2191

If you have a suggestion I am happy to hear it, if you have time we can have a call and discuss that.

Have a nice day.

Best Regards,
Ahmad El Masri

**Comment by Josverl** [comment]
I think you are trying to combine 2 issues, but I originating in two different pieces of code.

I'd suggest fixing the pymakr missing ABI85 binding separate from integrating a new version of the serialport module.

That will provide quicker results, but and allow serial port to fix and test any issues that may be there.

Note that the automated tests that I provided earlier clearly showed to me which updates failed the tests even before attempting integration


Jos

**Comment by Josverl** [comment]
Hi Ahmad,

just checking on how you solved this and if there is something that I can help with to improve the bindings generation and testing ?
 - I see that you went back to serialport 9.0.1
 - and I assume you manually generated the bindings as they are not published by the serialport project 

mp-download currently does not try to build bindings if they are missing , 
but i think that should be could be added. need to work out how to combine the bindings from the githuib actions on the different platform in a single PR , but I think that can be solved.

wrt to automated testing - not sure what can be done without a [self hosted runner](https://github.com/actions/runner#github-actions-runner) either physical or with a SerialEmulator (/platform) to run at least a connect test

**Comment by elmasria** [comment]
Hi @Josverl 

I reverted back to 9.0.1 to match with the master branch and generated the bindings manually using different operating systems. 

The issue is for that specific version (v85) the mp-download was generating bindings that for some reason throw an error when trying to connect to the board. 

Yeah, I agree with you about finding a way to combine the bindings from the GitHub actions on the different platforms in a single PR.

Have a nice day.

Ahmad EL Masri

**Review by Xykon — APPROVED** [review]

**Pull request merged**
