### PR TITLE
Fix/dependencies

### LINKED ISSUE #34: Development environment \incorrect dependencies
## The steps to reproduce this issue?

1. On windows 10
2. Clone the repo 
2. npm install --save-dev babel-core

## What happens?

C:\develop\repro\pymakr-vsc>npm install --save-dev babel-core
npm ERR! code ETARGET
npm ERR! notarget No matching version found for parser-regex@^1.0.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'serialport'
npm ERR! notarget

image

An indeed there is no 1.0.5 version on NPM 

npm view parser-regex 
shows that the latest: 1.0.2

A similar error is shown in my regular environment.

## What were you expecting to happen?
environment to work 

## Any other comments?
This may have to do with different version of the serial library, as I tried to experiment with multiple version of that a while ago. I assumed I cleaned that all up , but there may be stray libraries.

## What versions of software are you using?

**Operating system:**

**VSCode version:**
n/a

**Pymakr version:**
https://github.com/pycom/pymakr-vsc.git

### PR DESCRIPTION
**Pull request by Josverl**
This seems to fix #34 , however I have needed to : 

* manually remove references to the non-exeisten dependent 1.0.5 versions from both 
** package.json 
** package-lock.json

## Any other comments?
this does not seem a good way to fix this , on the other hand not being able to build and package the solution is not acceptable either.

as I do no understand in detail how the serial library was rebuild in v1.0.6 37c243d3423a70f37cd5e9e1078cb5bd7283bb37  ; this seems to be an acceptable solution.

It should also be checked that this has no ill effects on the building of the seriallib.

also ; when I run `vsce package` this creates a serialport.node file in the /output folder ; but not sure how to use / verify this.

## Where has this been tested?
only on my machine  :-) 

**Operating system:**

**VSCode version:**

**Pymakr version:**

### CODE REVIEW

**Comment by RalphHogenbirk** [comment]
Commented on issue #34 with my 2 cents on the problem :) I will try updating serialport and re-building everything as you suggest. 

"also ; when I run vsce package this creates a serialport.node file in the /output folder ; but not sure how to use / verify this."
Does it? It should simply create the vsix file that includes whatever you build / installed inside your package folder, including the already compiled serialport.node. Right?

**Comment by RalphHogenbirk** [comment]
By the way, how come there are a bunch of commits from oct 2018 linked to this pull request? Seems like those are already merged.

**Comment by Josverl** [comment]
🤔 That should not be the case, but I struggled to find a solution. I'll try to rebuild and send a better pr

Regards,
Jos Verlinde

________________________________

**Comment by RalphHogenbirk** [comment]
Have a look at my commit in branch 'serialport-7.1' (https://github.com/pycom/pymakr-vsc/commit/9903098be96be124e54b7542f7918cd793a5b796). Changes I made are:
- Updated to serialport 7.1.4
- Installing serialport through package.json instead of scripts/install.js
- precompiles/serialport-<os> folders only contain a precompiled bindings.node file
- On install, the bindings file in node_modules/@serialport/bindings/build/Release is overwritten with the precompile

This fixes your above issue, but also helps a little with issue #31.

I've yet to test it a bit more and also include the other precompiles besides osx

**Comment by Josverl** [comment]
Hi Ralph,


  *
cleaned up / replaced the PR with a new one #37
  *
tried the serialport upgrade
     *
checkout seralport-7.1
     *
npm install
this throws an error ;
see : https://gist.github.com/Josverl/f2f3a8b9ce5b3884022d9258e6390951

I tried to (<https://github.com/Josverl/pymakr-vsc/commits?author=Josverl> fixup install for win (winx64)<https://github.com/Josverl/pymakr-vsc/commit/fbf995f6b2a6cdda0ef467f9e0cd2b511c65e908>)

  *
fix a few mistakes in the windows path
  *
the source / target paths seem to be swapped ?
  *
there seems to be a logic error in that the copy is tried before the rebuild ? ( again , i don't grok cb inception to well )

If I run :
'C:\develop\pymakr-vsc>.\node_modules\.bin\electron-rebuild -f -w serialport -v 3.1.6 '
the results show up in the copy target rather than the source


I also saw a '-a osx' that may allow for a for cross platform compile , but need to figure out how to install the dependencies for that

/jos



________________________________

**Pull request closed without merging**
