### PR TITLE
fix: Change busy icon from lock  to spinning sync to indicate up/download in progress

### PR DESCRIPTION
**Pull request by Josverl**
Helps users to identify that something is in progress as mentioned in https://github.com/pycom/pymakr-vsc/issues/232

ref: https://code.visualstudio.com/api/references/icons-in-labels#animation

### CODE REVIEW

**Comment by jakobrosenberg** [comment]
Looks great. Are you able to rename the commit message to `fix: change busy icon from lock to spinning sync`? The `fix: ` prefix will trigger semantic-release to push a new release.

**Comment by Josverl** [comment]
Sure , rename is easy 
I was also considering possible use of  either: 

- Notification withProgress 
  https://github.com/Microsoft/vscode-extension-samples/tree/main/progress-sample#progress-sample
- showing progress in the status bar and Hide this when the action is finished  
  https://code.visualstudio.com/api/ux-guidelines/status-bar#progress-status-bar-item
  
In both cases the status can be updated to show the filenames as they are uploaded / downloaded  
that would give the nearly same progress functionality as V1, but using the VSCode API and UX rather than depending on terminal output

**Comment by jakobrosenberg** [comment]
We're using notification withProgress for some actions, but I think it might be too intrusive for those running persistent scripts.

Also, I think we might be talking about different things. The busy state isn't restricted to just upload/download. It shows whenever a script is currently running. That said, to create a withProgress for download/upload would be straight forward.

**Comment by Josverl** [comment]
OK , then please merge this as is. 
I've resolved the (version) conflicts

**Pull request merged**
