### PR TITLE
Updated bindings

### PR DESCRIPTION
**Pull request by pedroknup**
Downloaded new binding binaries matching with the new VSC versions. 
Removed "Deploy" stage from Github Actions. Since the deploys are being made manually (have to), this stage is unnecessary.

### CODE REVIEW

**Comment by jirikrepl** [comment]
are you sure that we need all of those `*.gipy` files?

**Comment by pedroknup** [comment]
Not sure. They were automatically generated by node-gyp. I'll confirm that.

**Comment by jirikrepl** [comment]
I know we merged this already, but did we need to add those files? or will they be generated automatically during some build process? thank you

**Comment by pedroknup** [comment]
I removed these files and added them in .gitignore and .vscodeignore.
Just created a PR with that.

**Pull request merged**
