### PR TITLE
Fix/downloads of multiple files from the board 

### PR DESCRIPTION
**Pull request by Josverl**
(Hi! 👋 Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

## What does this implement/fix? Explain your changes.

1) add missing import for module sys making the file listing fail in odd cases 
2) avoid leaking file handles on download, which caused downloads of more than 5-6 files to fail due to running out of file handles  `( with open(…) as f: )`
3) improve errorhandling on downloads by looking for telltale error string
4) make getFreeMemory work on standard micropython to increase the reach for other boards 

## Does this close any currently open issues?
No , i did not open issues for these.

## Where has this been tested?

Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Pymaker 1.0.7 + Serialport 7.1

### CODE REVIEW

**Comment by RalphHogenbirk** [comment]
Awesome work again @Josverl, I like the mcu_root_folder setting, which will also allow you to upload to the /sd folder instead of /flash. I'll check it out and test it. I see one or two small todo's in there, do you want me to fix that or are you working on them already?

Somehow git linked some of my commits from the serialport-7.1 branch to this pull request. Probably not an issue though, I'll merge that branch into master as well anyway.

**Comment by Josverl** [comment]
Hi Ralph, I suspect that is to do with the fact that your serialport 7.1 branch is the only one that would build for me, and while i tried to rebase, that threw up all kinds or artefacts with the serialport rebuild across platforms that i'd rather not get started on.

Im quite busy with my day job over the coming week, so appreciate if you could take a look at dealing with the last few hardcoded '/flash/' paths.

And indeed; it works for /sd or other devices as well if you mount them;
however not for both /flash AND /sd at the same time. 

Also I noticed that the py_ignore list is only used on upload ; not on download. 

I suspect that with up/downloading the `project.pymakr` file,  the sync logic sometimes gets confused and I need to manually delete that file before download detects any new files on the board.
So i think there should be a way to force a resync / or to prevent that file from downloading (if that is indeed the root cause)

**Comment by RalphHogenbirk** [comment]
Ok, no issues. I will merge my 7.1 branch to master before I merge yours, then it should not cause any issues I think. I'll fix the hardcoded /flash paths as well, no issue. 

I was aware that the py_ignore is not used on download. Usually when something is in the py_ignore, it won't end up on the board anyway, so on download it wouldn't matter. But maybe in some situations it does, if you accidentally uploaded something before adding it to py_ignore. 

I didn't know the issue with project.pymakr and the sync logic getting confused about new files on the board. Will try to replicate and investigate.

**Comment by Josverl** [comment]
would it be it possible to run a script at the intial connect to determine the firmware's storage config ?
then something like : 
``` python
# Determine the root folder of the device 
import os
try:
    _ = os.stat('/flash')
    r = "/flash"
except OSError as e:
    if e.args[0] == errno.ENOENT:
        r = os.getcwd()
finally:
    print("'{}'".format(r))
```
 can help set the mcu_root_folder

**Comment by RalphHogenbirk** [comment]
Good idea @Josverl. We could run that before each upload (on initial connect we don't have the guarantee that the REPL is available, user code might be running). Then the mcu_root_folder could be removed from user settings and just be a dynamic variable in the code.

FYI latest state of your branch is in https://github.com/pycom/pymakr-vsc/tree/Josverl-fix/downloads. Just fixed a few small things. Both serialport-7.1 and your download branch have been merged to develop as well.

**Comment by Josverl** [comment]
Checking Before download indeed makes more sense. Upload already worked most of the times as that was relative to the current directory.
But perhaps we need to make sure the detection works across ports or make it simple to update the script, or allow the config to override.

I like the ux feedback on the folder used as well as that avoids mistakes.


Regards,
Jos Verlinde

________________________________

**Comment by RalphHogenbirk** [comment]
@Josverl Added the automatic detection. Seems to work as far as I have the boards to test it. Any feedback before I merge develop to master? https://github.com/pycom/pymakr-vsc/commit/d636646aaaca8ac8c58fb8189f8bb3c8c87710be

**Comment by Josverl** [comment]
Hi Ralph,

I needed to change my system setup in order to build, perhaps good to document these steps in the ## Develop Section 
- as SU / Admin : `npm install -g node-gyp`
- Follow the instuctions on : https://github.com/nodejs/node-gyp to install the required toolchain and SDKs, or to resolve any missing components / config.

[ in my case the 'Windows SDK version 10.0.17763.0' needed to be added ]

**Comment by Josverl** [comment]
After building I still had some issues with downloading from a board:  after cranking up de logging it looks like there are some characters after the detected folder name. `os.listdir: /flash/`

'''
[Extension Host] [info] Pyboard | Entering raw repl (at Logger.log (c:\develop\pymakr-vsc\lib\helpers\logger.js:39:17))
console.ts:134 [Extension Host] [verbose] Pyboard | Executing code:
import os, errno
try:
    r = "/flash"
    _ = os.stat(r)
except OSError as e:
    if e.args[0] == errno.ENOENT:
        r = os.getcwd()
finally:
    print("'{}'".format(r))
 (at Logger.log (c:\develop\pymakr-vsc\lib\helpers\logger.js:39:17))
console.ts:134 [Extension Host] [info] Pyboard | Soft reset (at Logger.log (c:\develop\pymakr-vsc\lib\helpers\logger.js:39:17))
console.ts:134 [Extension Host] [info] ShellWorkers | os.listdir: /flash/ (at Logger.log (c:\develop\pymakr-vsc\lib\helpers\logger.js:39:17))
console.ts:134 [Extension Host] [verbose] Pyboard | Executing code:import ubinascii, sys, os
list = ubinascii.hexlify(str(os.listdir('/flash/')))
sys.stdout.write(list)

 (at Logger.log (c:\develop\pymakr-vsc\lib\helpers\logger.js:39:17))
'''

**Comment by Josverl** [comment]
I think I found another another minor error in the reporting; i think `Downloading **to**` should be `Downloading from`

``` text
Downloading project (main folder)...
Not safe booting, disabled in settings

Downloading to /flash...
```
cause appears to be a strcmp that is case sensitive ; fix is .toLowerCase()

```
        var direction = "to"
        if(_this.method_action.toLowerCase() == "download"){
          direction = "from"
        }
```

**Comment by Josverl** [comment]
see : https://github.com/Josverl/pymakr-vsc/tree/fix/dowloads_1.10

**Comment by RalphHogenbirk** [comment]
@Josverl nice catch! Thanks for helping out once again with some updated code. I will implement it and release on Monday (I have a day off today)

**Comment by RalphHogenbirk** [comment]
@Josverl merged and released!

**Pull request merged**
