### PR TITLE
Add runselection

### PR DESCRIPTION
**Pull request by Josverl**
## What does this implement/fix? Explain your changes.
- Run a line or block of code 
- resets selection to editor 
- removes excess indentation before running.
- key-bindings to Ctrl-Shift-Enter to mimic VSCode's  Python key-binding of Shift-Enter  
- suggested updates to readme and changelog 

## Does this close any currently open issues?
Implements #17 

## Where has this been tested?

**Operating system:**
Microsoft Windows [Version 10.0.17763.1]
**VSCode version:**
Version: 1.28.0 (system setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-05T14:58:53.203Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Pymakr version:**
1.0.5 (Private build)

### CODE REVIEW

**Comment by RalphHogenbirk** [comment]
Thanks again for this pull! I've tested them and they work, but I've re-arranged the code a bit to fit with what was already there in board/runner.py. I've moved most logic there, and instead of using paste-mode i've used the existing pyboard.run function that does the same (only using raw-repl). 

You can check the changes I made here and test them if you want. https://github.com/pycom/pymakr-vsc/commit/b8078e09e1a334dc3cbdd5728b071f599f2150ca

**Comment by RalphHogenbirk** [comment]
Added one more quick feature: when using the normal 'run' command but the user has made a selection, run that selection only.

Code: https://github.com/pycom/pymakr-vsc/commit/f2896dd01ab40bb21ae9882a57782b6632e39e87

**Comment by RalphHogenbirk** [comment]
Let me know if you think this still works like you intended. If so, I can merge this to the master branch and include it in the next release.

**Comment by Josverl** [comment]
Thanks Ralph, 
the changes make sense to me , Ill give it a run through and keep you posted. 
About when is a next release planned ?

**Comment by RalphHogenbirk** [comment]
Nice, thanks for the expanded tests!

2) Got it, i've merged it to my local test branch already, will include it to master when we release.

3) Interesting, that's indeed an argument for using paste mode over raw repl. But I also agree with your point 5 that raw-repl is more clean, and it's specially purposed for executing python from code (the nodejs code of the plugin in this case), which are the reasons I removed your paste mode method. Let me run some tests with paste mode again, see if we can clean that up a bit.

4) Yes, this extra line has been the case for a long time. Pretty much a seperate issue, but I also couldn't fine the issue yet. It acts like there is an extra line at the start, but we're not adding it as far as I found.

5) agreed, as mentioned in 4). I don't have the funny characters you are describing when running 'import uos as os' as you say. I suspect this is a windows specific thing (I'm testing on osx).

**Comment by RalphHogenbirk** [comment]
Nice, thanks for the expanded tests!

2) Got it, i've merged it to my local test branch already, will include it to master when we release.

3) Interesting, that's indeed an argument for using paste mode over raw repl. But I also agree with your point 5 that raw-repl is more clean, and it's specially purposed for executing python from code (the nodejs code of the plugin in this case), which are the reasons I removed your paste mode method. Let me run some tests with paste mode again, see if we can clean that up a bit.

4) Yes, this extra line has been the case for a long time. Pretty much a seperate issue, but I also couldn't fine the issue yet. It acts like there is an extra line at the start, but we're not adding it as far as I found.

5) agreed, as mentioned in 4). I don't have the funny characters you are describing when running 'import uos as os' as you say. I suspect this is a windows specific thing (I'm testing on osx).

**Comment by RalphHogenbirk** [comment]
Nice, thanks for the expanded tests!

2) Got it, i've merged it to my local test branch already, will include it to master when we release.

3) Interesting, that's indeed an argument for using paste mode over raw repl. But I also agree with your point 5 that raw-repl is more clean, and it's specially purposed for executing python from code (the nodejs code of the plugin in this case), which are the reasons I removed your paste mode method. Let me run some tests with paste mode again, see if we can clean that up a bit.

4) Yes, this extra line has been the case for a long time. Pretty much a seperate issue, but I also couldn't fine the issue yet. It acts like there is an extra line at the start, but we're not adding it as far as I found.

5) agreed, as mentioned in 4). I don't have the funny characters you are describing when running 'import uos as os' as you say. I suspect this is a windows specific thing (I'm testing on osx).

**Comment by RalphHogenbirk** [comment]
Nice, thanks for the tests!

2) Got it, i've merged it to my local test branch already, will include it to master when we release.

3) Interesting, that's indeed an argument for using paste mode over raw repl. But I also agree with your point 5 that raw-repl is more clean, and it's specially purposed for executing python from code (the nodejs code of the plugin in this case), which are the reasons I removed your paste mode method. Let me run some tests with paste mode again, see if we can clean that up a bit.

4) Yes, this extra line has been the case for a long time. Pretty much a seperate issue, but I also couldn't fine the issue yet. It acts like there is an extra line at the start, but we're not adding it as far as I found.

5) agreed, as mentioned in 4). I don't have the funny characters you are describing when running 'import uos as os' as you say. I suspect this is a windows specific thing (I'm testing on osx).

**Comment by RalphHogenbirk** [comment]
Hi @Josverl, thanks again for the response!

I typed a complete response back, but github failed to post it, I lost the text and I was too lazy to re-type, so I just started coding:

Here's a merged branch with all latest code. This commit changes back to paste-mode for running selections. I made one adaption: Hiding the output from paste mode to make it look the same as raw mode. I did this by using 'wait_for_blocking' to wait for the last line of the selection to come back, followed by the '===', to detect when the print of the code ends and code output begins. I'm still testing it, but it seems to work fine.
https://github.com/pycom/pymakr-vsc/commit/d1a8bdf3434d90a5378d812e454990a5601ea44b

About 4), I've encountered this before and also couldn't find what is causing the traceback to be 1 line off. We find the same issue in paste mode though. The atom plugin also has the same issue. It seems like we're not sending any enter at the start of the code. It has the same behaviour over serial as well as over wifi, so it's not an issue in the serialport library. Something to look at, though it's a separate topic.

**Comment by Josverl** [comment]
1.  Got it, i've merged it to my local test branch already, will include it to master when we release.
> Thanks
  2.  Interesting, that's indeed an argument for using paste mode over raw repl. But I also agree with your point 5 that raw-repl is more clean, and it's specially purposed for executing python from code (the nodejs code of the plugin in this case), which are the reasons I removed your paste mode method. Let me run some tests with paste mode again, see if we can clean that up a bit.
> I would like the two to be both available :
     *   The current RUN command would continue to use RAW-Repl
     *   The Run Selected would use Paste-Mode
  3.  Yes, this extra line has been the case for a long time. Pretty much a seperate issue, but I also couldn't fine the issue yet. It acts like there is an extra line at the start, but we're not adding it as far as I found.
     *   Yeah , could not find it either , but did not want to open too many issues at once ….
  4.  agreed, as mentioned in 4). I don't have the funny characters you are describing when running 'import uos as os' as you say. I suspect this is a windows specific thing (I'm testing on osx).
     *   Hmm, just thinking out loud, perhaps its a code table or a unicode / ascii conversion issue ?

/jos

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by RalphHogenbirk** [comment]
2) Yes, I implemented that. check it out:
https://github.com/pycom/pymakr-vsc/commit/d1a8bdf3434d90a5378d812e454990a5601ea44b

3) No problems with opening many issues. Better to have it registered as an open issue whenever someone else is looking at the same issue :)

4) Could be, will look in to this

**Comment by Josverl** [comment]
Hoi Ralph,

Like the thinkign behind using paste mode and supressing the output to the terminal, but the implementaion in d1a8bdf<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpycom%2Fpymakr-vsc%2Fcommit%2Fd1a8bdf3434d90a5378d812e454990a5601ea44b&data=02%7C01%7C%7C9e8e9c5671f144182a8708d638ba5b8f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636758770374451381&sdata=UnhltsdfpI6He7Fj1YW19FhH1Hd7A5QQEe7pnyv1gHo%3D&reserved=0> is not stable.
Im not sure if that is the serial code that changed, or something else.

The terminal sops working , or stops displaying code , when pasting lager blocks of code ( say over 25 lines )
Getting back in a working state then is at least a pycmakr.disconnect > pycmakr.connect or a vscode Reload Window and sometimes a MCU recycle

Ive tried to tease the 2 changes apart to provide better test results, but my Git skills fail me ☹

Ill try again tonight

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
