### PR TITLE
Fix/serial multi platform

### LINKED ISSUE #58: permanent Fix for the serialport problem
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.
see issues #4 #11 #28 #42 #53 #54 
When vscode updates to an electron version that has a different ABI, the serialport module breaks 
These updates seem to come unexpected for end-users.

## Describe the solution you'd like
during packaging add the native bindings for : 
- multiple platforms 
- multiple electron versions ( ABI versions more specifically) 
this can be done by a script ( approx 200 lines of ps1 code) 

- test against the insiders build of vscode to pre-empt version changes , and publish updates containing updated native bindings, before they are rolled out to the general public 

this would need to be done by an automated build/test system 
the reference uses Azure Pipelines which is free for open source projects such as pymakr.

This is described in the reference implementation documented at :
 https://github.com/Josverl/pymakr-vsc/blob/fix/SerialMultiPlatform/doc/multiplatform%20support.md#multiplatform-support

## Describe alternatives you've considered
see the discussion on #53 

## Proposed implementation
im working on a [PR](https://github.com/Josverl/pymakr-vsc/tree/fix/SerialMultiPlatform) , but as it is quite large, may need to work to bring it into shape.

### PR DESCRIPTION
**Pull request by Josverl**
This PR intends to implement a permanent solution to resolve the serialport update problems across platforms and future VSCode upgrades 

Approach: 
* During development a powershell script is used to download the native modules for all relevant versions of VSCode/Electron/Node and stored in a native_modules folder.
* This native_modules folder should be checked in to Git
* A postinstall script copies the modules to node_modules
* On require('serialport') the correct modules are automagically loaded from the respective folders , using the VSCode runtime ABI , platform and architecture.
* This functionality is/was already provided by the bindings module that is used by the serialport module to load the (correct) bindings.node native file ( naming can be confusing, I admit) 

in addition additional steps have been added to the packaging (vsce package) , 
- to avoid to much files to be packaged, 
- and to ensure that the native files **are** include

- a start has been made to add automated tests to aid in automated testing using azure Pipelines (free of charge for public repros), but this is work in progress.

More extensive documentation can be found in the /docs folder of this  PR
Note that it should be tested on multiple platforms before a final merge.

I have tried to rebase/merge the different commits into a single large one , but my GIT skill fail me on that one. 

/Jos 

## Does this close any currently open issues?
This should Fix #58 ( and  #4 #11 #28 #42 #53 #54) 

## Where has this been tested?
Windows 10, VSCode current , VSCode Insider 
I have not(yet) tested with VSCode x64.

**VSCode (32 bit)** 
Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Pymakr**
1.1.4 (this PR)

### CODE REVIEW

**Comment by Josverl** [comment]
note that while testing it turned out that a number of the precompiled serialport bindings@2.0.8 were actually not working for electron@5.x.x 
see Issue : https://github.com/serialport/node-serialport/issues/1920 

perhaps its worth taking a look at a the @latest version and focus on that insted.
ill wait for you to return to work before i proceed any further

**Comment by pedroknup** [comment]
Awesome job @Josverl! 

I've been studying this PR but I'm facing some problems. I'll continue studying it, following your documentation and the code itself, a bit longer. If I can't get rid of the problems by myself, I may need your help again. Your solution is amazing.

Thank you for contributing to the project.

**Comment by Josverl** [comment]
@BradenM ,

FYI: this PR has the scripts and documentation with regards to a lot of the testing / validation of the bindings.

I also have simple electron app to test serialport bindings in isolation running against any electron version, but that recently started failing on linux due to some crash/security related changes in chrome.
happy to share that on a seperate branch.

**Comment by BradenM** [comment]
Awesome, thanks. 

When I get behind a desktop later tonight I'll go ahead and provide you with updated Linux and macOS bindings for now and start working on a pipeline for this.

**Comment by Josverl** [comment]
wrt to the testing:
also see : https://stackoverflow.com/questions/57621585/how-can-i-determine-the-abi-version-and-other-details-of-a-compiled-native-mod

and : https://github.com/Josverl/electron-serialport
which is a minimal electron app adapted for testing the bindings

**Comment by BradenM** [comment]
@Josverl

I've got the absolute minimum up and running [here](https://github.com/BradenM/pymakr-vsc/commit/97f96af83b416c765e7796aaaf71ff1506a1b2b0/checks?check_suite_id=304535145). Still need to add the testing and committing of the bindings, but am I heading in the correct direction here?

Haven't had time to read completely through your documentation yet (which is thankfully very extensive!), so still trying to wrap my head around all this haha.

**Comment by Josverl** [comment]
Looks good Braden,

Can you change the matrix to build / test for different electron versions ?
(that is the trip-up every time, the node version does not come into play)
Lets start by static , but we can read the electron versions used by vscode ( at least I reverse engineered something that works on the VSCode Tags and the contents on a yarn file )

/Jos

**Comment by BradenM** [comment]
Can you link me to the script you wrote for detecting the electron versions? (I'm on mobile right now  :/)

With that it should be simple to write an action to execute it.

**Comment by BradenM** [comment]
@Josverl,

Am I correct in saying that `mp-download.ps1` compiles bindings for the environment it's executed in? Or does it only download precompiled ones?

If so, could we simply change [this line](https://github.com/BradenM/pymakr-vsc/blob/5214618588ae3a6f80c012685ce6df006f2213b9/.github/workflows/main.yml#L29) in the workflow to: `npx pwsh ./scripts/mp-download.ps1`, merge the resulting `./native_modules` folder from each environment, then commit?

**Comment by BradenM** [comment]
Update - opened a draft PR over at Josverl/pymakr-vsc#2 for further discussion.

**Comment by Josverl** [comment]
@pedroknup,

@BradenM and Myself have been collaborating on a CI/CD using Github actions.
that is now running on my fork (and on Bradens) and seems to be working quite OK 
https://github.com/Josverl/pymakr-vsc/blob/master/doc/builds.md

in some cases ( dependabot) it is running too many test instances bit other than that is seems to be working fine.

while it is by no means a complete test suite at least it provides assurance that : 
- pymakr-vsc can build on 3 platforms 
- the serialport works on the current and next version of electron on 3 platforms (x64 only for now)

**Comment by pedroknup** [comment]
That's great! I also have been working on the previous version.
Let's do it. Please create a PR.

**Comment by Josverl** [comment]
Ok ,
glad to do that.

There are quite a few commits, partly in order to test the CI/CD you need to to a commit,
And also cause we needed to run into some issues before finding simple capiltilisation errors.

I propose  do some cherry piking to split out 2 PRs:

  *   CI/CD build and electron-test using Github Actions
  *   Update of dependencies
based on dependabot and npm audit and confidence gained by the above tests

Makes sense ?

Which of the pycom branches should I target ?
[cid:image002.png@01D5A05B.ED7036C0]

Jos Verlinde
+31 (6) 51 44 68 44 | +31 (20) 500 1227 | Jos.Verlinde@microsoft.com<mailto:Jos.Verlinde@microsoft.com>

**Comment by Josverl** [comment]
And perhaps there is also an opportunity to automate the release process

https://github.com/marketplace/actions/vscode-release-plugin

to replace/augment process in publish.md

Jos Verlinde
+31 (6) 51 44 68 44 | +31 (20) 500 1227 | Jos.Verlinde@microsoft.com<mailto:Jos.Verlinde@microsoft.com>

From: Jos Verlinde
Sent: donderdag 21 november 2019 11:08
To: pycom/pymakr-vsc <reply@reply.github.com>; pycom/pymakr-vsc <pymakr-vsc@noreply.github.com>
Cc: State change <state_change@noreply.github.com>
Subject: RE: [pycom/pymakr-vsc] Fix/serial multi platform (#59)

Ok ,
glad to do that.

There are quite a few commits, partly in order to test the CI/CD you need to to a commit,
And also cause we needed to run into some issues before finding simple capiltilisation errors.

I propose  do some cherry piking to split out 2 PRs:

  *   CI/CD build and electron-test using Github Actions
  *   Update of dependencies
based on dependabot and npm audit and confidence gained by the above tests

Makes sense ?

Which of the pycom branches should I target ?
[cid:image001.png@01D5A05D.430AC680]

Jos Verlinde
+31 (6) 51 44 68 44 | +31 (20) 500 1227 | Jos.Verlinde@microsoft.com<mailto:Jos.Verlinde@microsoft.com>

**Comment by pedroknup** [comment]
Yes it does, let's to it.
That's a nice idea. I'll definitely work on an automated extension release process once we have the compatibility problem solved, which is the major problem.

**Comment by BradenM** [comment]
I should also note that currently an automatic release is setup to be executed if a branch with `release` in its name (i.e `release/vX.X.X` or `release/*`) is pushed. For this to succeed, a github secret needs to be added under the name `VSCE_TOKEN` referenced the personal access token used for publishing. For docs on adding a secret see [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#creating-encrypted-secrets). See [here](https://github.com/Josverl/pymakr-vsc/blob/be0ad70047bf9df90f3f7157ac6bfb62895cb075/.github/workflows/main.yml#L74) to take a look at at the release workflow.

Also, the workflow automatically publishes a `pymakr-nightly.vsix` package everyday at 1am UTC. This can be seen [here](https://github.com/Josverl/pymakr-vsc/commit/be0ad70047bf9df90f3f7157ac6bfb62895cb075/checks?check_suite_id=321370443). Currently it just uploads the `.vsix` as a build artifact which can be downloaded by whomever, but it can be uploaded anywhere else if you have a better idea in mind.

**Pull request closed without merging**
